# MULTI CLASS IMAGE CLASSIFICTION

In [ ]:
import tensorflow as tf
from keras.applications import MobileNetV2
from keras.datasets import cifar10
from keras.models import Sequential
from keras.layers import Flatten, Dense
from keras.optimizers import Adam
from keras.utils import to_categorical

In [ ]:
(train_images, train_labels), (test_images, test_labels) = cifar10.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

# train_labels = to_categorical(train_labels, num_classes=10)
# test_labels = to_categorical(test_labels, num_classes=10)

170498071/170498071 [==============================] - 5s 0us/step


In [ ]:
print("Training data size",len(train_labels), "with 5000 of each class")
print("Test data size",len(test_labels),"with 1000 of each class")

Training data size 50000 with 5000 of each class
Test data size 10000 with 1000 of each class


In [ ]:
base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(32, 32, 3))


9406464/9406464 [==============================] - 1s 0us/step


In [ ]:
model = Sequential()
model.add(base_model)
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(train_images, train_labels, epochs=5, validation_data=(test_images, test_labels))

Epoch 1/5
1563/1563 [==============================] - 343s 208ms/step - loss: 1.2917 - accuracy: 0.5606 - val_loss: 1.4595 - val_accuracy: 0.5122
Epoch 2/5
1563/1563 [==============================] - 346s 221ms/step - loss: 0.9784 - accuracy: 0.6723 - val_loss: 1.1687 - val_accuracy: 0.6672
Epoch 3/5
1563/1563 [==============================] - 323s 206ms/step - loss: 0.9408 - accuracy: 0.6818 - val_loss: 1.5601 - val_accuracy: 0.5467
Epoch 4/5
1563/1563 [==============================] - 317s 203ms/step - loss: 0.8842 - accuracy: 0.6990 - val_loss: 2.1716 - val_accuracy: 0.3180
Epoch 5/5
1563/1563 [==============================] - 339s 217ms/step - loss: 0.8651 - accuracy: 0.7098 - val_loss: 1.0049 - val_accuracy: 0.6975


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 mobilenetv2_1.00_224 (Func  (None, 1, 1, 1280)        2257984   
 tional)                                                         
                                                                 
 flatten_1 (Flatten)         (None, 1280)              0         
                                                                 
 dense_2 (Dense)             (None, 256)               327936    
                                                                 
 dense_3 (Dense)             (None, 10)                2570      
                                                                 
Total params: 2588490 (9.87 MB)
Trainable params: 2554378 (9.74 MB)
Non-trainable params: 34112 (133.25 KB)
_________________________________________________________________


In [ ]:
model.save('mobileNetV2.keras')

In [ ]:
from tensorflow.keras.applications import DenseNet121
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D

base_model = DenseNet121(weights='imagenet', include_top=False, input_shape=(32, 32, 3))

model = Sequential()
model.add(base_model)
model.add(GlobalAveragePooling2D())
model.add(Dense(256, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])


29084464/29084464 [==============================] - 0s 0us/step


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 densenet121 (Functional)    (None, 1, 1, 1024)        7037504   
                                                                 
 global_average_pooling2d (G  (None, 1024)             0         
 lobalAveragePooling2D)                                          
                                                                 
 dense (Dense)               (None, 256)               262400    
                                                                 
 dense_1 (Dense)             (None, 10)                2570      
                                                                 
Total params: 7,302,474
Trainable params: 7,218,826
Non-trainable params: 83,648
_________________________________________________________________


In [ ]:
model.fit(train_images, to_categorical(train_labels), epochs=5, validation_data=(test_images, to_categorical(test_labels)))

Epoch 1/5
1563/1563 [==============================] - 1104s 697ms/step - loss: 1.1613 - accuracy: 0.6000 - val_loss: 1.5193 - val_accuracy: 0.5220
Epoch 2/5
1563/1563 [==============================] - 1060s 678ms/step - loss: 1.0046 - accuracy: 0.6521 - val_loss: 4.3186 - val_accuracy: 0.2901
Epoch 3/5
1563/1563 [==============================] - 1052s 673ms/step - loss: 0.9023 - accuracy: 0.6900 - val_loss: 1.3615 - val_accuracy: 0.5634
Epoch 4/5
1563/1563 [==============================] - 1071s 685ms/step - loss: 0.8721 - accuracy: 0.6974 - val_loss: 4.4227 - val_accuracy: 0.5267
Epoch 5/5
1563/1563 [==============================] - 1075s 688ms/step - loss: 1.1671 - accuracy: 0.5888 - val_loss: 1.0078 - val_accuracy: 0.6422


In [ ]:
model.save('denseNetV2.keras')

In [ ]:
model1 = tf.keras.models.load_model('multi_class_model.keras')
model2 = tf.keras.models.load_model('mobileNetV2.keras')
model3 = tf.keras.models.load_model('denseNetV2.keras')

In [ ]:
model1.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 15, 15, 32)        0         
 D)                                                              
                                                                 
 conv2d_1 (Conv2D)           (None, 13, 13, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPoolin  (None, 6, 6, 64)          0         
 g2D)                                                            
                                                                 
 flatten (Flatten)           (None, 2304)              0         
                                                                 
 dense (Dense)               (None, 64)                1

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
import numpy as np

predictions = model1.predict(test_images, steps=len(test_images), verbose=1)



10000/10000 [==============================] - 24s 2ms/step


In [ ]:
pred_classes = [np.argmax(element) for element in predictions]
conf_matrix = confusion_matrix(test_labels, pred_classes)

print("Confusion Matrix for Model:")
print(conf_matrix)

Confusion Matrix for Model:
[[641  12  46  33  20   7  10  15 155  61]
 [ 14 763   5  13   5   6   8   0  51 135]
 [ 59   7 572  81  87  55  63  45  20  11]
 [ 22  12  69 557  65 125  58  40  24  28]
 [ 17   7  69  72 662  28  54  75  11   5]
 [  9   3  41 214  43 581  24  53  18  14]
 [  2   6  41  81  35  15 791   7  10  12]
 [ 14   3  25  49  54  44   6 775   6  24]
 [ 36  16  13  14   5   3   3  10 868  32]
 [ 11  49   7  15   4   8   5  20  46 835]]


In [ ]:
predictions2=model2.predict(test_images, steps=len(test_images), verbose=1)
pred_classes = [np.argmax(element) for element in predictions]

conf_matrix = confusion_matrix(test_labels, pred_classes)

print("Confusion Matrix for Model:")
print(conf_matrix)

10000/10000 [==============================] - 88s 9ms/step
Confusion Matrix for Model:
[[641  12  46  33  20   7  10  15 155  61]
 [ 14 763   5  13   5   6   8   0  51 135]
 [ 59   7 572  81  87  55  63  45  20  11]
 [ 22  12  69 557  65 125  58  40  24  28]
 [ 17   7  69  72 662  28  54  75  11   5]
 [  9   3  41 214  43 581  24  53  18  14]
 [  2   6  41  81  35  15 791   7  10  12]
 [ 14   3  25  49  54  44   6 775   6  24]
 [ 36  16  13  14   5   3   3  10 868  32]
 [ 11  49   7  15   4   8   5  20  46 835]]


In [ ]:

from sklearn.metrics import confusion_matrix,classification_report

flat_confusion_matrix = [item for sublist in conf_matrix for item in sublist]

target_names = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

report = classification_report(test_labels, pred_classes, target_names=target_names)

print(report)

              precision    recall  f1-score   support

    airplane       0.78      0.64      0.70      1000
  automobile       0.87      0.76      0.81      1000
        bird       0.64      0.57      0.61      1000
         cat       0.49      0.56      0.52      1000
        deer       0.68      0.66      0.67      1000
         dog       0.67      0.58      0.62      1000
        frog       0.77      0.79      0.78      1000
       horse       0.75      0.78      0.76      1000
        ship       0.72      0.87      0.79      1000
       truck       0.72      0.83      0.77      1000

    accuracy                           0.70     10000
   macro avg       0.71      0.70      0.70     10000
weighted avg       0.71      0.70      0.70     10000



In [ ]:
predictions2=model3.predict(test_images, steps=len(test_images), verbose=1)
pred_classes = [np.argmax(element) for element in predictions2]

conf_matrix = confusion_matrix(test_labels, pred_classes)

print("Confusion Matrix for Model:")
print(conf_matrix)

Confusion Matrix for Model:
[[710  14  33  14  56  20  37  10  67  39]
 [ 37 735   3   3   4   7  30   2  35 144]
 [ 90   2 340  46 195  68 193  43   7  16]
 [ 29   8  26 416 158  57 216  46  15  29]
 [ 23   2  12  15 752  10 139  36   7   4]
 [ 13  13  46 219 138 330 118  99  10  14]
 [  7   1  15  27  35   3 894   8   5   5]
 [ 20   4  16  30 126  31  38 706   2  27]
 [117  22   3  11  25   4  27   6 736  49]
 [ 41  64   6   4  20  11  17   5  29 803]]


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

flat_confusion_matrix = [item for sublist in conf_matrix for item in sublist]

target_names = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

report = classification_report(test_labels, pred_classes, target_names=target_names)

print(report)

              precision    recall  f1-score   support

    airplane       0.65      0.71      0.68      1000
  automobile       0.85      0.73      0.79      1000
        bird       0.68      0.34      0.45      1000
         cat       0.53      0.42      0.47      1000
        deer       0.50      0.75      0.60      1000
         dog       0.61      0.33      0.43      1000
        frog       0.52      0.89      0.66      1000
       horse       0.73      0.71      0.72      1000
        ship       0.81      0.74      0.77      1000
       truck       0.71      0.80      0.75      1000

    accuracy                           0.64     10000
   macro avg       0.66      0.64      0.63     10000
weighted avg       0.66      0.64      0.63     10000

